version: "3"
services:
  web: &web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - '.env'

  db:
    image: postgres
    volumes:
      - ./db/postgres-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - './redis-data:/data'

  sidekiq:
    build: .
    volumes:
      - .:/myapp
      - '/myapp/tmp' # don't mount tmp directory
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec sidekiq -C config/sidekiq.yml"
    env_file:
      - '.env'

volumes:
  redis:
  postgres: