default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

dev_test: &dev_test
  <<: *default
  port: 5432
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  <<: *dev_test

test:
  <<: *default
  <<: *dev_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>